FROM node:18-alpine AS base

WORKDIR /app

COPY package.json .

COPY . .

RUN npm i

FROM base AS server

WORKDIR /app

COPY --from=base /app /app

RUN apk --no-cache add git 

CMD ["sh"]