name: DEPLOY
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm i
      - name: env production
        run: |
          touch .env.production
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          file: Dockerfile.prod
          tags: gabrielsoaresdev/boilerplate-vite-react:latest
      - name: Update image in stack
        uses: distributhor/workflow-webhook@v2
        env:
         webhook_url: ${{secrets.WEB_HOOK_DOCKER_URL}}
         webhook_secret: "Y0uR5ecr3t"
         verify_ssl: false